CREATE TABLE [IF NOT EXISTS] Book (
    ISBN VARCHAR(17) PRIMARY KEY,
    CountryCode CHAR(2) NOT NULL,
    FOREIGN KEY (CountryCode) REFERENCES Country(CountryCode) 
);

CREATE TABLE [IF NOT EXISTS] Song (
  SongID INTEGER NOT NULL PRIMARY KEY,
  Title TEXT NOT NULL,
  CountryCode CHAR(2) NOT NULL,
  FOREIGN KEY (CountryCode) REFERENCES Country(CountryCode)  
);

CREATE TABLE [IF NOT EXISTS] Artist (
    SongID INTEGER NOT NULL PRIMARY KEY,
    ArtistID INTEGER NOT NULL,
    FOREIGN KEY (ArtistID) REFERENCES ArtistDetails(ArtistID)
);

CREATE TABLE [IF NOT EXISTS] ArtistDetails (
    ArtistID INTEGER NOT NULL PRIMARY KEY,
    Name TEXT NOT NULL
);

CREATE TABLE [IF NOT EXISTS] Country (
    CountryCode CHAR(2) NOT NULL PRIMARY KEY,
    Name TEXT NOT NULL
);